language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'

# command to install dependancies
install:
  - sudo bash install.sh

script:
  - python3 main_driver.py zip.csv
  - python3 main_driver.py train_zip.csv test_zip.csv 0
